import org.jetbrains.kotlin.utils.addToStdlib.applyIf
import java.net.URL
import java.time.OffsetDateTime
import java.time.format.DateTimeFormatter
import java.util.UUID

/**
 * The JVM version we're currently targeting, or compiling to.
 */
val targetVersion = JavaVersion.VERSION_1_8

/**
 * The JVM version we're writing the project in.
 * Usually the same as the [targetVersion].
 */
val sourceVersion = JavaVersion.VERSION_1_8

/**
 * Whether we should generate an `api` source set.
 */
val generateApiSourceSet = true

// Project plugins, set up from the `buildSrc/.../plugins.kt` file.
plugins {
    api.plugin.PLUGINS.forEach {
        id(it.id)
            .also { dep ->
                if (it.version != api.plugin.CORE_VERSION) {
                    dep.version(it.version)
                }
            }
            .apply(it.defaultApply)
    }
}

// Adds an `include` configuration corresponding to ShadowJar.
// Every dependency using the `include` configuration will be included (or
// 'shaded') in the output JAR, producing a fat-jar (or uber-jar).
configurations {
    val include by creating

    // don't include in maven pom
    compileOnly.get().extendsFrom(include)

    // but also work in tests
    testImplementation.get().extendsFrom(include)
}

// Maven Repositories
repositories {
    mavenLocal()
    mavenCentral()

    api.repdep.REPOSITORIES.forEach {
        if (it.layout != null) {
            ivy {
                url = it.urls[0]
                layout(it.layout.toString())
            }
        } else if (it.urls[0].toString().startsWith("http")) {
            maven {
                url = it.urls[0]
                it.artifactUrls.forEach { url -> artifactUrls(url) }
            }
        } else flatDir { dirs(*it.urls) }
    }
}

// Project dependencies, set up from the `buildSrc/.../repdeps.kt` file
dependencies {
    api.repdep.DEPENDENCIES.forEach {
        if (it.config == api.repdep.UNDEFINED_CONFIG) {
            throw Exception(
                "Dependency ${it.name} did not have any associated config."
            )
        }

        it.config(it.group, it.name, it.version)
    }
}

/**
 * The group of the current artifact, corresponding to what's written in the
 * [Coordinates] file in `buildSrc`.
 */
group = Coordinates.artifactGroup

/**
 * The version of the current artifact, corresponding to what's written in the
 * [Coordinates] file in `buildSrc`.
 */
version = Coordinates.version

// Generate the `api` source set
if (generateApiSourceSet) {
    sourceSets {
        val name = "api"

        val main by sourceSets
        val test by sourceSets

        val sourceSet = create(name) {
            java.srcDir("src/$name/kotlin")
            resources.srcDir("src/$name/resources")

            compileClasspath += main.compileClasspath
            runtimeClasspath += main.runtimeClasspath
        }

        arrayOf(main, test).forEach {
            it.compileClasspath += sourceSet.output
            it.runtimeClasspath += sourceSet.output
        }
    }
}

// The latest commit ID
val buildRevision: String = grgit.log()[0].id ?: "dev"

// Disable unneeded rules
ktlint {
    disabledRules.add("no-wildcard-imports")
}

blossom {
    val defaultReplacementMap = mutableMapOf<String, String>()

    Coordinates::class.java.declaredFields.filter {
        // Auto-generated by Kotlin as Coordinates is an object.
        it.name != "INSTANCE"
    }.forEach {
        defaultReplacementMap[
            "coordinates.${it.name}"
        ] = it.get(null) as String
    }

    defaultReplacementMap["coordinates.rev"] = buildRevision

    arrayOf(
        defaultReplacementMap,
        config.Blossom.replacementMap,
    ).forEach {
        it.forEach { (k, v) ->
            replaceToken(
                config.Blossom.replacementInputFormat.replace(
                    api.config.BLOSSOM_FORMAT_STRING,
                    k,
                ),
                config.Blossom.replacementOutputFormat.ifEmpty {
                    api.config.BLOSSOM_FORMAT_STRING
                }.replace(api.config.BLOSSOM_FORMAT_STRING, v),
            )
        }
    }
}

tasks {
    build { dependsOn(ktlintFormat) }
    test { useJUnitPlatform() }

    val targetString =
        (if (targetVersion.ordinal < 10) "1." else "") + targetVersion.majorVersion

    val sourceString =
        (if (sourceVersion.ordinal < 10) "1." else "") + sourceVersion.majorVersion

    // Configure JVM versions
    compileKotlin { kotlinOptions.jvmTarget = targetString }

    compileJava {
        targetCompatibility = targetString
        sourceCompatibility = sourceString
    }

    // Configure the documentation
    dokkaHtml {
        val moduleFile = File(
            projectDir,
            "MODULE.temp.${UUID.randomUUID()}.md"
        )

        // In order to have a description on the rendered docs, we have to have
        // a file with the # Module thingy in it. That's what we're
        // automagically creating and deleting here.
        run {
            doFirst {
                moduleFile.deleteOnExit()
                moduleFile.writeText(
                    "# Module ${Coordinates.name}\n${Coordinates.description}"
                )
            }

            doLast { moduleFile.delete() }
        }

        moduleName.set(Coordinates.name)

        dokkaSourceSets.configureEach {
            displayName.set("${Coordinates.name} on ${Coordinates.gitHost}")
            includes.from(moduleFile.path)

            skipDeprecated.set(false)
            includeNonPublic.set(false)
            skipEmptyPackages.set(true)
            reportUndocumented.set(true)
            suppressObviousFunctions.set(true)

            // Link the source to the documentation
            sourceLink {
                localDirectory.set(file("src"))
                remoteUrl.set(URL("${Coordinates.gitUrl}/tree/trunk/src"))
            }

            /**
             * @see config.Dokka.externalDocumentations
             */
            config.Dokka.externalDocumentations.forEach {
                externalDocumentationLink { url.set(URL(it)) }
            }
        }
    }

    // The main artifact, we just have to add the API source output and the
    // LICENSE file.
    jar {
        // Java distribution stuff
        val javaVersion = System.getProperty("java.version")
        val javaVendor = System.getProperty("java.vendor")
        val jvmVersion = System.getProperty("java.vm.version")

        // Build time & date
        val (buildDate, buildTime) = OffsetDateTime.now().run {
            arrayOf(
                DateTimeFormatter.ISO_LOCAL_DATE.format(this),
                DateTimeFormatter.ofPattern("HH:mm:ss.SSSZ").format(this)
            )
        }

        // Normalizing project version
        val prettyProjectVersion = project.version.toString().run {
            Regex("(\\d+\\.\\d+\\.\\d+).*").matchEntire(this)
                ?.run { groupValues[1] }
                ?: throw Error(
                    "Version '$this' does not match version pattern, e.g. 1.0.0-QUALIFIER"
                )
        }

        with(Coordinates) {
            manifest.attributes(
                "Created-By" to "$javaVersion ($javaVendor $jvmVersion)",
                "Build-Date" to buildDate,
                "Build-Time" to buildTime,
                "Build-Revision" to buildRevision,
                "Specification-Title" to project.name,
                "Specification-Version" to prettyProjectVersion,
                "Specification-Vendor" to vendor,
                "Implementation-Title" to name,
                "Implementation-Version" to version,
                "Implementation-Vendor" to vendor,
                "Bundle-Name" to name,
                "Bundle-Description" to description,
                "Bundle-DocURL" to gitUrl,
                "Bundle-Vendor" to vendor,
                "Bundle-SymbolicName" to "$artifactGroup.$name",
                //"Main-Class" to "", TODO: Create an annotation for the main class or file to be filled here
            )
        }

        if (generateApiSourceSet) {
            from(sourceSets["api"].output)
        }

        from("LICENSE")
    }

    if (generateApiSourceSet) {
        // API artifact, only including the output of the API source and the
        // LICENSE file.
        create("apiJar", Jar::class) {
            group = "build"
            archiveClassifier.set("api")

            from(sourceSets["api"].output)
            from("LICENSE")
        }
    }

    // Source artifact, including everything the 'main' does but not compiled.
    create("sourcesJar", Jar::class) {
        group = "build"
        archiveClassifier.set("sources")

        from(sourceSets["main"].allSource)

        if (generateApiSourceSet) {
            from(sourceSets["api"].allSource)
        }

        from("LICENSE")
    }

    // The Javadoc artifact, containing the Dokka output and the LICENSE file.
    create("javadocJar", Jar::class) {
        group = "build"
        archiveClassifier.set("javadoc")

        val dokkaHtml by getting
        dependsOn(dokkaHtml)

        from(dokkaHtml)
        from("LICENSE")
    }

    // Configure ShadowJar
    shadowJar {
        val include by project.configurations

        configurations.clear()
        configurations += include

        archiveClassifier.set(if (config.ShadowJar.overrideJar) "" else "all")
        manifest.inheritFrom(jar.get().manifest)

        config.ShadowJar.packageRemappings.forEach { (k, v) -> relocate(k, v) }
    }

    afterEvaluate {
        // Task priority
        val publishToSonatype by getting
        val closeAndReleaseSonatypeStagingRepository by getting

        closeAndReleaseSonatypeStagingRepository
            .mustRunAfter(publishToSonatype)

        // Wrapper task since calling both one after the other in IntelliJ
        // seems to cause some problems.
        create("releaseToSonatype") {
            group = "publishing"

            dependsOn(
                publishToSonatype,
                closeAndReleaseSonatypeStagingRepository
            )
        }
    }
}

// Define the default artifacts' tasks
val defaultArtifactTasks = arrayOf("sourcesJar", "javadocJar")
    .applyIf(generateApiSourceSet) { plus("apiJar") }
    .map { tasks[it] }

// Declare the artifacts
artifacts {
    defaultArtifactTasks.forEach(::archives)
    archives(tasks.shadowJar)
}

publishing.publications {
    // Sets up the Maven integration.
    create("mavenJava", MavenPublication::class.java) {
        from(components["java"])
        defaultArtifactTasks.forEach(::artifact)

        with(Coordinates) {
            pom {
                name.set(name)
                description.set(this@with.description)
                url.set(gitUrl)

                with(Pom) {
                    licenses {
                        licenses.forEach {
                            license {
                                name.set(it.name)
                                url.set(it.url)
                                distribution.set(it.distribution)
                            }
                        }
                    }

                    developers {
                        developers.forEach {
                            developer {
                                id.set(it.id)
                                name.set(it.name)
                            }
                        }
                    }
                }

                scm {
                    connection.set("scm:git:git://$gitHost/$repoId.git")
                    developerConnection.set(
                        "scm:git:ssh://$gitHost/$repoId.git"
                    )
                    url.set(gitUrl)
                }
            }
        }

        // Configure the signing extension to sign this Maven artifact.
        signing.sign(this)
    }
}

// Configure publishing to Maven Central
nexusPublishing.repositories.sonatype {
    nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
    snapshotRepositoryUrl.set(
        uri(
            "https://s01.oss.sonatype.org/content/repositories/snapshots/"
        )
    )

    // Skip this step if environment variables NEXUS_USERNAME or NEXUS_PASSWORD
    // aren't set.
    username.set(properties["NEXUS_USERNAME"] as? String ?: return@sonatype)
    password.set(properties["NEXUS_PASSWORD"] as? String ?: return@sonatype)
}
