import java.net.URL
import java.time.OffsetDateTime
import java.time.format.DateTimeFormatter

/**
 * The JVM version we're currently targeting, or compiling to.
 */
val targetVersion = JavaVersion.VERSION_1_8

/**
 * The JVM version we're writing the project in.
 * Usually the same as the [targetVersion].
 */
val sourceVersion = JavaVersion.VERSION_1_8

/**
 * Whether we should generate an `api` source set.
 */
val generateApiSourceSet = true

// Project plugins, set up from the `buildSrc/.../plugins.kt` file
plugins {
    api.plugin.PLUGINS.forEach {
        id(it.id)
            .also { dep ->
                if (it.version != api.plugin.CORE_VERSION) {
                    dep.version(it.version)
                }
            }
            .apply(it.defaultApply)
    }
}

// Adds `include` configuration for ShadowJar
configurations {
    val include by creating

    // don't include in maven pom
    compileOnly.get().extendsFrom(include)

    // but also work in tests
    testImplementation.get().extendsFrom(include)
}

// Maven Repositories
repositories {
    mavenLocal()
    mavenCentral()

//    Repositories.mavenUrls.forEach(::maven)
}

// Project dependencies, set up from the `buildSrc/.../dependencies.kt` file
dependencies {
    api.repdep.DEPENDENCIES.forEach {
        if (it.config == api.repdep.UNDEFINED_CONFIG) {
            throw Exception(
                "Dependency ${it.name} did not have any associated config."
            )
        }

        it.config(it.group, it.name, it.version)
    }
}

/**
 * The group of the current artifact, corresponding to what's written in the
 * [Coordinates] file in `buildSrc`.
 */
group = Coordinates.GROUP

/**
 * The version of the current artifact, corresponding to what's written in the
 * [Coordinates] file in `buildSrc`.
 */
version = Coordinates.VERSION

// Generate the `api` source set
if (generateApiSourceSet) {
    sourceSets {
        val name = "api"

        val main by sourceSets
        val test by sourceSets

        val sourceSet = create(name) {
            java.srcDir("src/$name/kotlin")
            resources.srcDir("src/$name/resources")

            compileClasspath += main.compileClasspath
            runtimeClasspath += main.runtimeClasspath
        }

        arrayOf(main, test).forEach {
            it.compileClasspath += sourceSet.output
            it.runtimeClasspath += sourceSet.output
        }
    }
}

// The latest commit ID
val buildRevision: String = grgit.log()[0].id ?: "dev"

// Disable unneeded rules
ktlint {
    disabledRules.add("no-wildcard-imports")
}

blossom {
    val defaultReplacementMap = mutableMapOf<String, String>()

    // Map all of [Coordinates]' fields to its corresponding camelCase
    // version.
    Coordinates::class.java.declaredFields.filter {
        // Auto-generated by Kotlin as Coordinates is an object.
        it.name != "INSTANCE"
    }.forEach {
        var name = "coordinates."
        var upperNext = false
        it.name.forEach { x ->
            if (x == '_') {
                upperNext = true
            } else {
                name += if (upperNext) x.toUpperCase() else x.toLowerCase()
                upperNext = false
            }
        }

        defaultReplacementMap[name] = it.get(null) as String
    }

    defaultReplacementMap["coordinates.rev"] = buildRevision

    arrayOf(
        defaultReplacementMap,
        config.Blossom.replacementMap,
    ).forEach {
        it.forEach { (k, v) ->
            replaceToken("@$k@", v)
        }
    }
}

tasks {
    test {
        useJUnitPlatform()
    }

    var targetString = targetVersion.majorVersion
    if (targetVersion.ordinal < 10) {
        targetString = "1.$targetString"
    }

    var sourceString = sourceVersion.majorVersion
    if (sourceVersion.ordinal < 10) {
        sourceString = "1.$sourceString"
    }

    // Configure JVM versions
    compileKotlin {
        kotlinOptions.jvmTarget = targetString
    }

    compileJava {
        targetCompatibility = targetString
        sourceCompatibility = sourceString
    }

    // Configure the documentation
    dokkaHtml {
        val moduleFile = File(projectDir, "MODULE.temp.md")

        // In order to have a description on the rendered docs, we have to have
        // a file with the # Module thingy in it. That's what we're
        // automagically creating and deleting here.
        run {
            doFirst {
                moduleFile.writeText(
                    "# Module ${Coordinates.NAME}\n${Coordinates.DESC}"
                )
            }

            doLast {
                moduleFile.delete()
            }
        }

        moduleName.set(Coordinates.NAME)

        dokkaSourceSets.configureEach {
            displayName.set("${Coordinates.NAME} on ${Coordinates.GIT_HOST}")
            includes.from(moduleFile.path)

            skipDeprecated.set(false)
            includeNonPublic.set(false)
            skipEmptyPackages.set(true)
            reportUndocumented.set(true)
            suppressObviousFunctions.set(true)

            // Link the source to the documentation
            sourceLink {
                localDirectory.set(file("src"))
                remoteUrl.set(
                    URL(
                        "https://${Coordinates.GIT_HOST}/${Coordinates.REPO_ID}/tree/trunk/src"
                    )
                )
            }

            // External documentation link template
//            externalDocumentationLink {
//                url.set(URL("https://javadoc.io/doc/net.java.dev.jna/jna/5.10.0/"))
//            }
        }
    }

    // The main artifact, we just have to add the API source output and the
    // LICENSE file.
    jar {
        fun normalizeVersion(versionLiteral: String): String {
            val match = Regex("(\\d+\\.\\d+\\.\\d+).*")
                .matchEntire(versionLiteral)

            require(match != null) {
                "Version '$versionLiteral' does not match version pattern, e.g. 1.0.0-QUALIFIER"
            }

            return match.groupValues[1]
        }

        val buildTimeAndDate = OffsetDateTime.now()

        val buildDate = DateTimeFormatter.ISO_LOCAL_DATE
            .format(buildTimeAndDate)
        val buildTime = DateTimeFormatter.ofPattern("HH:mm:ss.SSSZ")
            .format(buildTimeAndDate)

        val javaVersion = System.getProperty("java.version")
        val javaVendor = System.getProperty("java.vendor")
        val jvmVersion = System.getProperty("java.vm.version")

        with(Coordinates) {
            manifest.attributes(
                "Created-By" to "$javaVersion ($javaVendor $jvmVersion)",
                "Build-Date" to buildDate,
                "Build-Time" to buildTime,
                "Build-Revision" to buildRevision,
                "Specification-Title" to project.name,
                "Specification-Version" to normalizeVersion(project.version.toString()),
                "Specification-Vendor" to VENDOR,
                "Implementation-Title" to NAME,
                "Implementation-Version" to VERSION,
                "Implementation-Vendor" to VENDOR,
                "Bundle-Name" to NAME,
                "Bundle-Description" to DESC,
                "Bundle-DocURL" to "https://$GIT_HOST/$REPO_ID",
                "Bundle-Vendor" to VENDOR,
                "Bundle-SymbolicName" to "$GROUP.$NAME",
            )
        }

        if (generateApiSourceSet) {
            from(sourceSets["api"].output)
        }

        from("LICENSE")
    }

    if (generateApiSourceSet) {
        // API artifact, only including the output of the API source and the
        // LICENSE file.
        create("apiJar", Jar::class) {
            group = "build"
            archiveClassifier.set("api")

            from(sourceSets["api"].output)
            from("LICENSE")
        }
    }

    // Source artifact, including everything the 'main' does but not compiled.
    create("sourcesJar", Jar::class) {
        group = "build"
        archiveClassifier.set("sources")

        from(sourceSets["main"].allSource)

        if (generateApiSourceSet) {
            from(sourceSets["api"].allSource)
        }

        from("LICENSE")
    }

    // The Javadoc artifact, containing the Dokka output and the LICENSE file.
    create("javadocJar", Jar::class) {
        group = "build"
        archiveClassifier.set("javadoc")

        val dokkaHtml by getting
        dependsOn(dokkaHtml)

        from(dokkaHtml)
        from("LICENSE")
    }

    // Configure ShadowJar
    shadowJar {
        val include by project.configurations

        configurations.clear()
        configurations += include

        archiveClassifier.set(if (config.ShadowJar.overrideJar) "" else "all")
        manifest.inheritFrom(jar.get().manifest)

        config.ShadowJar.packageRemappings.forEach { (key, value) ->
            relocate(key, value)
        }
    }

    afterEvaluate {
        // Task priority
        val publishToSonatype by getting
        val closeAndReleaseSonatypeStagingRepository by getting
        closeAndReleaseSonatypeStagingRepository.mustRunAfter(publishToSonatype)

        // Wrapper task since calling both one after the other in IntelliJ seems to
        // cause some problems.
        create("releaseToSonatype") {
            group = "publishing"

            dependsOn(
                publishToSonatype,
                closeAndReleaseSonatypeStagingRepository
            )
        }
    }
}

// Define the default artifacts' tasks
val defaultArtifactTasks = arrayOf(
    tasks["sourcesJar"],
    tasks["javadocJar"]
).also {
    if (generateApiSourceSet) {
        it.plus(tasks["apiJar"])
    }
}

// Declare the artifacts
artifacts {
    defaultArtifactTasks.forEach(::archives)
    archives(tasks.shadowJar)
}

publishing.publications {
    // Sets up the Maven integration.
    create("mavenJava", MavenPublication::class.java) {
        from(components["java"])
        defaultArtifactTasks.forEach(::artifact)

        with(Coordinates) {
            pom {
                name.set(NAME)
                description.set(DESC)
                url.set("https://$GIT_HOST/$REPO_ID")

                with(Pom) {
                    licenses {
                        licenses.forEach {
                            license {
                                name.set(it.name)
                                url.set(it.url)
                                distribution.set(it.distribution)
                            }
                        }
                    }

                    developers {
                        developers.forEach {
                            developer {
                                id.set(it.id)
                                name.set(it.name)
                            }
                        }
                    }
                }

                scm {
                    connection.set("scm:git:git://$GIT_HOST/$REPO_ID.git")
                    developerConnection.set("scm:git:ssh://$GIT_HOST/$REPO_ID.git")
                    url.set("https://$GIT_HOST/$REPO_ID")
                }
            }
        }

        // Configure the signing extension to sign this Maven artifact.
        signing.sign(this)
    }
}

// Configure publishing to Maven Central
nexusPublishing.repositories.sonatype {
    nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
    snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))

    // Skip this step if environment variables NEXUS_USERNAME or NEXUS_PASSWORD aren't set.
    username.set(properties["NEXUS_USERNAME"] as? String ?: return@sonatype)
    password.set(properties["NEXUS_PASSWORD"] as? String ?: return@sonatype)
}
